### ISSUE TITLE
 i don't know hao to use it

### ISSUE THREAD

**Issue by WeiYu53111** [shikanon/socks5proxy#1]
please update the doc , i don't know hao to use it , thanks

**Comment by shikanon** [comment]
Usage of ./vpn_server_linux_amd64_v0.1:
  -local string
    	Input server listen address(Default 8888): (default ":18888")
  -passwd string
    	Input server proxy password: (default "123456")
  -type string
    	Input encryption type: (default "random")

**Comment by WeiYu53111** [comment]
Oh, thanks.

**Comment by WeiYu53111** [comment]
Em.......................And the client?

**Comment by shikanon** [comment]
use help command
